In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"D:\Dubai\Dubai_Updated_data\Raw_Data\Transactions.csv")
print('Loaded Transactions.csv rows:', df.shape[0])
df.head()

Loaded Transactions.csv rows: 1661875

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
0,3-9-2006-163,9,3,هبات,Gifts,هبه,Grant,16-10-2006,4,فيلا,...,NaN,0,3162.42,12000000.0,3794.56,NaN,NaN,3.0,1.0,0.0
1,3-9-2019-2944,9,3,هبات,Gifts,هبه,Grant,13-11-2019,1,أرض,...,NaN,0,209.09,916659.0,4384.04,NaN,NaN,2.0,4.0,0.0
2,2-13-1999-347,13,2,رهون,Mortgages,تسجيل رهن,Mortgage Registration,22-03-1999,1,أرض,...,NaN,0,1062.72,1200000.0,1129.18,NaN,NaN,1.0,1.0,0.0
3,2-13-2001-547,13,2,رهون,Mortgages,تسجيل رهن,Mortgage Registration,23-07-2001,2,مبنى,...,NaN,0,1393.55,3500000.0,2511.57,NaN,NaN,5.0,1.0,0.0
4,2-13-2020-9477,13,2,رهون,Mortgages,تسجيل رهن,Mortgage Registration,30-11-2020,2,مبنى,...,NaN,0,278.71,2500000.0,8969.90,NaN,NaN,1.0,1.0,0.0

In [2]:
df['trans_group_en'].value_counts()

trans_group_en
Sales        1272224
Mortgages     328311
Gifts          61340
Name: count, dtype: int64

In [3]:
df = df[df['trans_group_en'] == 'Sales']

In [4]:
df.columns

Index(['transaction_id', 'procedure_id', 'trans_group_id', 'trans_group_ar',
       'trans_group_en', 'procedure_name_ar', 'procedure_name_en',
       'instance_date', 'property_type_id', 'property_type_ar',
       'property_type_en', 'property_sub_type_id', 'property_sub_type_ar',
       'property_sub_type_en', 'property_usage_ar', 'property_usage_en',
       'reg_type_id', 'reg_type_ar', 'reg_type_en', 'area_id', 'area_name_ar',
       'area_name_en', 'building_name_ar', 'building_name_en',
       'project_number', 'project_name_ar', 'project_name_en',
       'master_project_en', 'master_project_ar', 'nearest_landmark_ar',
       'nearest_landmark_en', 'nearest_metro_ar', 'nearest_metro_en',
       'nearest_mall_ar', 'nearest_mall_en', 'rooms_ar', 'rooms_en',
       'has_parking', 'procedure_area', 'actual_worth', 'meter_sale_price',
       'rent_value', 'meter_rent_price', 'no_of_parties_role_1',
       'no_of_parties_role_2', 'no_of_parties_role_3'],
      dtype='object')

In [5]:
df['trans_group_en'].value_counts()

trans_group_en
Sales    1272224
Name: count, dtype: int64

In [6]:
df.head()

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
5,1-11-2013-15239,11,1,مبايعات,Sales,بيع,Sell,16-05-2013,4,فيلا,...,NaN,0,382.67,2000000.0,5226.44,NaN,NaN,1.0,1.0,0.0
6,1-4-2012-13,4,1,مبايعات,Sales,إضافة أرض بالبيع,Adding Land By Sell,19-04-2012,2,مبنى,...,NaN,0,346.81,920700.0,2654.77,NaN,NaN,1.0,1.0,0.0
9,1-11-2006-316,11,1,مبايعات,Sales,بيع,Sell,07-03-2006,2,مبنى,...,NaN,0,211.35,1900000.0,8989.83,NaN,NaN,9.0,1.0,0.0
10,1-11-2026-121,11,1,مبايعات,Sales,بيع,Sell,05-01-2026,2,مبنى,...,NaN,0,232.56,9011000.0,38746.99,NaN,NaN,13.0,1.0,0.0
11,1-11-2025-37635,11,1,مبايعات,Sales,بيع,Sell,09-09-2025,2,مبنى,...,NaN,0,211.51,13386000.0,63287.79,NaN,NaN,1.0,1.0,0.0

In [7]:
df['Year']=df['instance_date'].str[6:]
df['Year']

5          2013
6          2012
9          2006
10         2026
11         2025
           ...
1661868    2013
1661870    2017
1661871    2024
1661872    2012
1661873    2009
Name: Year, Length: 1272224, dtype: object

In [8]:
# First ensure instance_date is in datetime format
df['instance_date'] = pd.to_datetime(df['instance_date'], format='%d-%m-%Y', errors='coerce')

# Create Year column
df['Year'] = df['instance_date'].dt.year

# Create Quarter column in format "Q1 2022"
df['Quarter'] = 'Q' + df['instance_date'].dt.quarter.astype(str) + ' ' + df['instance_date'].dt.year.astype(str)

# Alternative: Create separate Quarter and Year Quarter columns if needed
df['Quarter_Year'] = df['instance_date'].dt.to_period('Q')

In [9]:
df

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3,Year,Quarter,Quarter_Year
5,1-11-2013-15239,11,1,مبايعات,Sales,بيع,Sell,2013-05-16,4,فيلا,...,2000000.0,5226.44,NaN,NaN,1.0,1.0,0.0,2013,Q2 2013,2013Q2
6,1-4-2012-13,4,1,مبايعات,Sales,إضافة أرض بالبيع,Adding Land By Sell,2012-04-19,2,مبنى,...,920700.0,2654.77,NaN,NaN,1.0,1.0,0.0,2012,Q2 2012,2012Q2
9,1-11-2006-316,11,1,مبايعات,Sales,بيع,Sell,2006-03-07,2,مبنى,...,1900000.0,8989.83,NaN,NaN,9.0,1.0,0.0,2006,Q1 2006,2006Q1
10,1-11-2026-121,11,1,مبايعات,Sales,بيع,Sell,2026-01-05,2,مبنى,...,9011000.0,38746.99,NaN,NaN,13.0,1.0,0.0,2026,Q1 2026,2026Q1
11,1-11-2025-37635,11,1,مبايعات,Sales,بيع,Sell,2025-09-09,2,مبنى,...,13386000.0,63287.79,NaN,NaN,1.0,1.0,0.0,2025,Q3 2025,2025Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661868,1-11-2013-19796,11,1,مبايعات,Sales,بيع,Sell,2013-06-26,3,وحدة,...,4150000.0,19593.03,NaN,NaN,1.0,1.0,0.0,2013,Q2 2013,2013Q2
1661870,1-45-2017-404,45,1,مبايعات,Sales,بيع حق منفعة,Sell Development,2017-06-12,2,مبنى,...,17400000.0,3203.97,NaN,NaN,1.0,1.0,0.0,2017,Q2 2017,2017Q2
1661871,1-11-2024-10269,11,1,مبايعات,Sales,بيع,Sell,2024-03-20,3,وحدة,...,3200000.0,25740.03,NaN,NaN,1.0,1.0,0.0,2024,Q1 2024,2024Q1
1661872,1-11-2012-23048,11,1,مبايعات,Sales,بيع,Sell,2012-12-05,4,فيلا,...,4950000.0,9359.75,NaN,NaN,1.0,1.0,0.0,2012,Q4 2012,2012Q4
1661873,1-102-2008-41398,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,2009-06-09,3,وحدة,...,1794176.0,21528.40,NaN,NaN,1.0,1.0,0.0,2009,Q2 2009,2009Q2

In [10]:
flat_types = {
    "Flat", "Villa", "Stacked Townhouses", "Unit"
}

shop_types = {
    "Shop", "Store", "Show Rooms"
}

office_types = {
    "Office", "Clinic", "Workshop", "Warehouse"
}

others = {
    "Hotel Apartment",
    "Hotel Rooms",
    "Gymnasium",
    "Sized Partition",
    "Hotel",
    "Building"
}
def categorize_property(sub_type):
    if sub_type in flat_types:
        return "Flat"
    elif sub_type in shop_types:
        return "Shop"
    elif sub_type in office_types:
        return "Office"
    else:
        return "Others"

    
df['property_type'] = df['property_sub_type_en'].apply(categorize_property)

In [11]:
df

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3,Year,Quarter,Quarter_Year,property_type
5,1-11-2013-15239,11,1,مبايعات,Sales,بيع,Sell,2013-05-16,4,فيلا,...,5226.44,NaN,NaN,1.0,1.0,0.0,2013,Q2 2013,2013Q2,Others
6,1-4-2012-13,4,1,مبايعات,Sales,إضافة أرض بالبيع,Adding Land By Sell,2012-04-19,2,مبنى,...,2654.77,NaN,NaN,1.0,1.0,0.0,2012,Q2 2012,2012Q2,Others
9,1-11-2006-316,11,1,مبايعات,Sales,بيع,Sell,2006-03-07,2,مبنى,...,8989.83,NaN,NaN,9.0,1.0,0.0,2006,Q1 2006,2006Q1,Others
10,1-11-2026-121,11,1,مبايعات,Sales,بيع,Sell,2026-01-05,2,مبنى,...,38746.99,NaN,NaN,13.0,1.0,0.0,2026,Q1 2026,2026Q1,Others
11,1-11-2025-37635,11,1,مبايعات,Sales,بيع,Sell,2025-09-09,2,مبنى,...,63287.79,NaN,NaN,1.0,1.0,0.0,2025,Q3 2025,2025Q3,Others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661868,1-11-2013-19796,11,1,مبايعات,Sales,بيع,Sell,2013-06-26,3,وحدة,...,19593.03,NaN,NaN,1.0,1.0,0.0,2013,Q2 2013,2013Q2,Flat
1661870,1-45-2017-404,45,1,مبايعات,Sales,بيع حق منفعة,Sell Development,2017-06-12,2,مبنى,...,3203.97,NaN,NaN,1.0,1.0,0.0,2017,Q2 2017,2017Q2,Others
1661871,1-11-2024-10269,11,1,مبايعات,Sales,بيع,Sell,2024-03-20,3,وحدة,...,25740.03,NaN,NaN,1.0,1.0,0.0,2024,Q1 2024,2024Q1,Flat
1661872,1-11-2012-23048,11,1,مبايعات,Sales,بيع,Sell,2012-12-05,4,فيلا,...,9359.75,NaN,NaN,1.0,1.0,0.0,2012,Q4 2012,2012Q4,Others
1661873,1-102-2008-41398,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,2009-06-09,3,وحدة,...,21528.40,NaN,NaN,1.0,1.0,0.0,2009,Q2 2009,2009Q2,Office

In [12]:
df=df[df['property_type_en']!='Land']
# df=df[df['Year'].isin([2020, 2021, 2022, 2023, 2024, 2025, 2026])]
df

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3,Year,Quarter,Quarter_Year,property_type
5,1-11-2013-15239,11,1,مبايعات,Sales,بيع,Sell,2013-05-16,4,فيلا,...,5226.44,NaN,NaN,1.0,1.0,0.0,2013,Q2 2013,2013Q2,Others
6,1-4-2012-13,4,1,مبايعات,Sales,إضافة أرض بالبيع,Adding Land By Sell,2012-04-19,2,مبنى,...,2654.77,NaN,NaN,1.0,1.0,0.0,2012,Q2 2012,2012Q2,Others
9,1-11-2006-316,11,1,مبايعات,Sales,بيع,Sell,2006-03-07,2,مبنى,...,8989.83,NaN,NaN,9.0,1.0,0.0,2006,Q1 2006,2006Q1,Others
10,1-11-2026-121,11,1,مبايعات,Sales,بيع,Sell,2026-01-05,2,مبنى,...,38746.99,NaN,NaN,13.0,1.0,0.0,2026,Q1 2026,2026Q1,Others
11,1-11-2025-37635,11,1,مبايعات,Sales,بيع,Sell,2025-09-09,2,مبنى,...,63287.79,NaN,NaN,1.0,1.0,0.0,2025,Q3 2025,2025Q3,Others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661868,1-11-2013-19796,11,1,مبايعات,Sales,بيع,Sell,2013-06-26,3,وحدة,...,19593.03,NaN,NaN,1.0,1.0,0.0,2013,Q2 2013,2013Q2,Flat
1661870,1-45-2017-404,45,1,مبايعات,Sales,بيع حق منفعة,Sell Development,2017-06-12,2,مبنى,...,3203.97,NaN,NaN,1.0,1.0,0.0,2017,Q2 2017,2017Q2,Others
1661871,1-11-2024-10269,11,1,مبايعات,Sales,بيع,Sell,2024-03-20,3,وحدة,...,25740.03,NaN,NaN,1.0,1.0,0.0,2024,Q1 2024,2024Q1,Flat
1661872,1-11-2012-23048,11,1,مبايعات,Sales,بيع,Sell,2012-12-05,4,فيلا,...,9359.75,NaN,NaN,1.0,1.0,0.0,2012,Q4 2012,2012Q4,Others
1661873,1-102-2008-41398,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,2009-06-09,3,وحدة,...,21528.40,NaN,NaN,1.0,1.0,0.0,2009,Q2 2009,2009Q2,Office

In [13]:
df['procedure_area_sqft']=df['procedure_area']*10.7639
df['sqft_sale_price']=df['meter_sale_price']/10.7639

C:\Users\Admin\AppData\Local\Temp\ipykernel_23220\835200220.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['procedure_area_sqft']=df['procedure_area']*10.7639
C:\Users\Admin\AppData\Local\Temp\ipykernel_23220\835200220.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sqft_sale_price']=df['meter_sale_price']/10.7639

In [14]:
import re
import pandas as pd

def map_to_bhk(val):
    if pd.isna(val):
        return None

    val = val.strip().upper()

    # Group large BHKs first
    if val in { "6 B/R","7 B/R", "8 B/R", "9 B/R"}:
        return ">5 B/R"

    # Match normal BHKs (1–6)
    match = re.match(r"(\d+)\s*B/R", val)
    if match:
        bhk = int(match.group(1))
        if bhk <= 5:
            return f"{bhk} B/R"

    # Special residential cases
    if val == "SINGLE ROOM":
        return "<1 B/R"

    else:
        return "Commercial"

df["BHK"] = df["rooms_en"].apply(map_to_bhk)

C:\Users\Admin\AppData\Local\Temp\ipykernel_23220\3192043834.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["BHK"] = df["rooms_en"].apply(map_to_bhk)

In [15]:
df

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3,Year,Quarter,Quarter_Year,property_type,procedure_area_sqft,sqft_sale_price,BHK
5,1-11-2013-15239,11,1,مبايعات,Sales,بيع,Sell,2013-05-16,4,فيلا,...,1.0,1.0,0.0,2013,Q2 2013,2013Q2,Others,4119.021613,485.552634,None
6,1-4-2012-13,4,1,مبايعات,Sales,إضافة أرض بالبيع,Adding Land By Sell,2012-04-19,2,مبنى,...,1.0,1.0,0.0,2012,Q2 2012,2012Q2,Others,3733.028159,246.636442,None
9,1-11-2006-316,11,1,مبايعات,Sales,بيع,Sell,2006-03-07,2,مبنى,...,9.0,1.0,0.0,2006,Q1 2006,2006Q1,Others,2274.950265,835.183344,None
10,1-11-2026-121,11,1,مبايعات,Sales,بيع,Sell,2026-01-05,2,مبنى,...,13.0,1.0,0.0,2026,Q1 2026,2026Q1,Others,2503.252584,3599.716645,None
11,1-11-2025-37635,11,1,مبايعات,Sales,بيع,Sell,2025-09-09,2,مبنى,...,1.0,1.0,0.0,2025,Q3 2025,2025Q3,Others,2276.672489,5879.633776,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661868,1-11-2013-19796,11,1,مبايعات,Sales,بيع,Sell,2013-06-26,3,وحدة,...,1.0,1.0,0.0,2013,Q2 2013,2013Q2,Flat,2279.901659,1820.253811,3 B/R
1661870,1-45-2017-404,45,1,مبايعات,Sales,بيع حق منفعة,Sell Development,2017-06-12,2,مبنى,...,1.0,1.0,0.0,2017,Q2 2017,2017Q2,Others,58456.157564,297.658841,None
1661871,1-11-2024-10269,11,1,مبايعات,Sales,بيع,Sell,2024-03-20,3,وحدة,...,1.0,1.0,0.0,2024,Q1 2024,2024Q1,Flat,1338.168048,2391.329351,1 B/R
1661872,1-11-2012-23048,11,1,مبايعات,Sales,بيع,Sell,2012-12-05,4,فيلا,...,1.0,1.0,0.0,2012,Q4 2012,2012Q4,Others,5692.596154,869.550070,None
1661873,1-102-2008-41398,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,2009-06-09,3,وحدة,...,1.0,1.0,0.0,2009,Q2 2009,2009Q2,Office,897.063426,2000.055742,Commercial

In [16]:
df.to_csv(r"D:\Dubai\Dubai_Updated_data\Transactions_Filtered.csv", index=False)

In [ ]:
# df=pd.read_csv("D:\Dubai Data\Location leve summary\Sales_with_Year_2020_2026.csv")
# df

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Sagar\AppData\Local\Temp\ipykernel_13768\3830563176.py:1: SyntaxWarning: invalid escape sequence '\D'
  df=pd.read_csv("D:\Dubai Data\Location leve summary\Sales_with_Year_2020_2026.csv")

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3,Year,Quarter,Quarter_Year,property_type,procedure_area_sqft,sqft_sale_price,BHK
0,1-11-2025-36691,11,1,مبايعات,Sales,بيع,Sell,2025-09-04,2,مبنى,...,1.0,2.0,0.0,2025,Q3 2025,2025Q3,Others,2275.165543,3076.698966,NaN
1,1-11-2023-24638,11,1,مبايعات,Sales,بيع,Sell,2023-08-18,2,مبنى,...,14.0,1.0,0.0,2023,Q3 2023,2023Q3,Others,2274.950265,2197.850222,NaN
2,1-11-2025-22014,11,1,مبايعات,Sales,بيع,Sell,2025-05-29,2,مبنى,...,1.0,1.0,0.0,2025,Q2 2025,2025Q2,Others,55662.494958,1320.458198,NaN
3,1-11-2024-25411,11,1,مبايعات,Sales,بيع,Sell,2024-07-10,4,فيلا,...,1.0,2.0,0.0,2024,Q3 2024,2024Q3,Others,2491.950489,2889.303134,NaN
4,1-11-2025-21741,11,1,مبايعات,Sales,بيع,Sell,2025-05-27,4,فيلا,...,1.0,1.0,0.0,2025,Q2 2025,2025Q2,Others,16365.971755,336.063137,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658807,1-102-2025-128612,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,2025-12-16,3,وحدة,...,1.0,1.0,0.0,2025,Q4 2025,2025Q4,Flat,392.989989,2009.674932,Commercial
658808,1-11-2023-9778,11,1,مبايعات,Sales,بيع,Sell,2023-04-03,4,فيلا,...,1.0,1.0,0.0,2023,Q2 2023,2023Q2,Others,7499.962603,323.067847,NaN
658809,1-41-2022-3813,41,1,مبايعات,Sales,بيع مبدئى,Delayed Sell,2022-03-08,4,فيلا,...,1.0,1.0,0.0,2022,Q1 2022,2022Q1,Others,2338.457275,576.876411,NaN
658810,1-11-2024-48145,11,1,مبايعات,Sales,بيع,Sell,2024-12-12,3,وحدة,...,1.0,2.0,0.0,2024,Q4 2024,2024Q4,Flat,474.365073,1264.848243,Commercial
658811,1-11-2021-13603,11,1,مبايعات,Sales,بيع,Sell,2021-08-05,4,فيلا,...,1.0,1.0,0.0,2021,Q3 2021,2021Q3,Others,3330.350660,810.725666,NaN

In [17]:
df['Year'].value_counts()

Year
2025    193311
2024    164771
2023    118306
2022     83114
2013     62701
2009     62097
2021     53216
2014     53164
2017     42352
2015     39296
2016     37404
2012     35592
2019     35341
2010     33587
2020     31061
2018     30197
2011     27872
2026     23363
2008     20553
2007      7937
2004      2258
2006      2193
2005      1932
2003      1686
2002      1540
2001       963
2000       539
1998       507
1999       448
1997         9
1993         1
1975         1
Name: count, dtype: int64

In [21]:
df['property_type_en'].value_counts()

property_type_en
Unit        971878
Villa       179551
Building     15883
Name: count, dtype: int64

In [22]:
df['property_sub_type_en'].value_counts()

property_sub_type_en
Flat                  867236
Villa                 103181
Office                 54215
Hotel Apartment        23774
Shop                   13386
Hotel Rooms            11925
Workshop                 431
Stacked Townhouses       358
Store                    299
Building                 145
Warehouse                121
Clinic                    53
Show Rooms                45
Hotel                     12
Gymnasium                  9
Sized Partition            7
Parking                    4
Unit                       2
Name: count, dtype: int64

In [23]:
df['property_type'].value_counts()

property_type
Flat      970777
Others    127985
Office     54820
Shop       13730
Name: count, dtype: int64

In [24]:
df['property_type'].isnull().sum()

np.int64(0)

In [22]:
df['project_name_en'].isnull().sum()

np.int64(65299)

In [25]:
df.columns

Index(['transaction_id', 'procedure_id', 'trans_group_id', 'trans_group_ar',
       'trans_group_en', 'procedure_name_ar', 'procedure_name_en',
       'instance_date', 'property_type_id', 'property_type_ar',
       'property_type_en', 'property_sub_type_id', 'property_sub_type_ar',
       'property_sub_type_en', 'property_usage_ar', 'property_usage_en',
       'reg_type_id', 'reg_type_ar', 'reg_type_en', 'area_id', 'area_name_ar',
       'area_name_en', 'building_name_ar', 'building_name_en',
       'project_number', 'project_name_ar', 'project_name_en',
       'master_project_en', 'master_project_ar', 'nearest_landmark_ar',
       'nearest_landmark_en', 'nearest_metro_ar', 'nearest_metro_en',
       'nearest_mall_ar', 'nearest_mall_en', 'rooms_ar', 'rooms_en',
       'has_parking', 'procedure_area', 'actual_worth', 'meter_sale_price',
       'rent_value', 'meter_rent_price', 'no_of_parties_role_1',
       'no_of_parties_role_2', 'no_of_parties_role_3', 'Year', 'Quarter',
       'Quarter_Year', 'property_type', 'procedure_area_sqft',
       'sqft_sale_price', 'BHK'],
      dtype='object')

In [26]:
df['property_type_en'].value_counts()

property_type_en
Unit        971878
Villa       179551
Building     15883
Name: count, dtype: int64

df

df

In [26]:
df

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3,Year,Quarter,Quarter_Year,property_type,procedure_area_sqft,sqft_sale_price,BHK
0,1-11-2025-36691,11,1,مبايعات,Sales,بيع,Sell,2025-09-04,2,مبنى,...,1.0,2.0,0.0,2025,Q3 2025,2025Q3,Others,2275.165543,3076.698966,NaN
1,1-11-2023-24638,11,1,مبايعات,Sales,بيع,Sell,2023-08-18,2,مبنى,...,14.0,1.0,0.0,2023,Q3 2023,2023Q3,Others,2274.950265,2197.850222,NaN
2,1-11-2025-22014,11,1,مبايعات,Sales,بيع,Sell,2025-05-29,2,مبنى,...,1.0,1.0,0.0,2025,Q2 2025,2025Q2,Others,55662.494958,1320.458198,NaN
3,1-11-2024-25411,11,1,مبايعات,Sales,بيع,Sell,2024-07-10,4,فيلا,...,1.0,2.0,0.0,2024,Q3 2024,2024Q3,Others,2491.950489,2889.303134,NaN
4,1-11-2025-21741,11,1,مبايعات,Sales,بيع,Sell,2025-05-27,4,فيلا,...,1.0,1.0,0.0,2025,Q2 2025,2025Q2,Others,16365.971755,336.063137,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658807,1-102-2025-128612,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,2025-12-16,3,وحدة,...,1.0,1.0,0.0,2025,Q4 2025,2025Q4,Flat,392.989989,2009.674932,Commercial
658808,1-11-2023-9778,11,1,مبايعات,Sales,بيع,Sell,2023-04-03,4,فيلا,...,1.0,1.0,0.0,2023,Q2 2023,2023Q2,Others,7499.962603,323.067847,NaN
658809,1-41-2022-3813,41,1,مبايعات,Sales,بيع مبدئى,Delayed Sell,2022-03-08,4,فيلا,...,1.0,1.0,0.0,2022,Q1 2022,2022Q1,Others,2338.457275,576.876411,NaN
658810,1-11-2024-48145,11,1,مبايعات,Sales,بيع,Sell,2024-12-12,3,وحدة,...,1.0,2.0,0.0,2024,Q4 2024,2024Q4,Flat,474.365073,1264.848243,Commercial
658811,1-11-2021-13603,11,1,مبايعات,Sales,بيع,Sell,2021-08-05,4,فيلا,...,1.0,1.0,0.0,2021,Q3 2021,2021Q3,Others,3330.350660,810.725666,NaN